// Code generated by github.com/siongleng89/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/siongleng89/gqlgen/_examples/scalars/external"
)

type Address struct {
	ID       external.ObjectID `json:"id"`
	Location *Point            `json:"location,omitempty"`
}
