#!/bin/bash

set -euo pipefail

gqlgen_dir=$(pwd)
cd $(mktemp -d)
go mod init inittest
printf '// +build tools\npackage tools\nimport _ "github.com/siongleng89/gqlgen"' | gofmt > tools.go
go mod tidy
go mod edit -replace=github.com/siongleng89/gqlgen="$gqlgen_dir"
go mod tidy

if ! go run github.com/siongleng89/gqlgen init ; then
    echo "gqlgen init failed"
    exit 125
fi

if ! go run github.com/siongleng89/gqlgen generate ; then
    echo "gqlgen generate failed"
    exit 125
fi
